"use client";

import { motion } from "framer-motion";
import { Flame, ThermometerSun, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface RoastCardProps {
    roastLevel: "mild" | "spicy" | "brutal";
    roastText: string;
}

const levelConfig = {
    mild: {
        icon: ThermometerSun,
        label: "Mild Roast",
        color: "text-french-blue dark:text-cool-sky",
    },
    spicy: {
        icon: Flame,
        label: "Spicy Roast",
        color: "text-orange-500",
    },
    brutal: {
        icon: Zap,
        label: "Brutal Roast",
        color: "text-red-500",
    },
};

export default function RoastCard({ roastLevel, roastText }: RoastCardProps) {
    const config = levelConfig[roastLevel] || levelConfig.spicy;
    const Icon = config.icon;

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="neo overflow-hidden border-none"
        >
            <div className="bg-gradient-to-br from-french-blue/5 to-cool-sky/5 p-8 sm:p-10">
                <div className="mb-8 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <div className="h-14 w-14 flex items-center justify-center rounded-2xl neo-interactive">
                            <Icon className={`h-7 w-7 ${config.color}`} />
                        </div>
                        <div>
                            <h3 className="text-xl font-bold text-foreground">AI Career Roast</h3>
                            <p className="text-sm font-medium text-muted-foreground">Devastatingly honest feedback</p>
                        </div>
                    </div>
                    <Badge className="neo-sm bg-background border-none px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-french-blue">
                        {config.label}
                    </Badge>
                </div>

                <div className="relative p-8 rounded-3xl neo-pressed bg-background/50 border-none">
                    <div className="absolute -left-2 top-10 h-10 w-1 rounded-full bg-french-blue" />
                    <div className="space-y-6">
                        {roastText.split("\n").filter(p => p.trim()).map((paragraph, i) => (
                            <p
                                key={i}
                                className="text-base sm:text-lg leading-relaxed text-foreground font-medium italic opacity-90"
                            >
                                "{paragraph}"
                            </p>
                        ))}
                    </div>
                </div>

                <div className="mt-8 flex items-center gap-3 px-2">
                    <div className="h-2 w-2 rounded-full bg-french-blue animate-pulse" />
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">
                        Generated by Career Intelligence Engine v2.0
                    </p>
                </div>
            </div>
        </motion.div>
    );
}
